Feature 124/quit logic
dnd-side-project/dnd-5th-5-backend pull request #183
Opened 2021-08-28 15:02 UTC by alertjjm

- 친구들의 friend info를 리스트로 가져와서 한번씩 찌르면서 삭제 대상의 id를 지워줌

2021-08-28 16:00 UTC, Catnap421 reviewed
멤버 삭제하는 방향으로 짜보는거야?

2021-08-28 16:00 UTC, Catnap421 commented on src/main/java/com/meme/ala/domain/event/component/EventHandler.java
> +                .removeIf(f -> f == deletedMember.getId());
FriendInfo의 getRelation 메서드로 관계 파악해서 지워줘도 괜찮을 거 같아

2021-08-28 16:03 UTC, Catnap421 requested changes

2021-08-28 16:03 UTC, Catnap421 commented on src/main/java/com/meme/ala/domain/event/component/EventHandler.java
> +    public void flushFriendInfo(Member targetMember, Member deletedMember) {
이벤트 핸들러에 있기보단 FriendInfoService로 옮기는 게 맞을 거 같아!

2021-08-29 07:01 UTC, alertjjm commented
> 멤버 삭제하는 방향으로 짜보는거야?

아니아니 멤버 disable해줘도 나중에 비즈니스 로직상에 버그를 없애기 위해서는 aggregation, friend정보들을 다 찔러서 없애줘야된다고생각했어. 전부다 예외처리로 하는거보다 깔끔해보여서

2021-08-29 07:01 UTC, alertjjm commented on src/main/java/com/meme/ala/domain/event/component/EventHandler.java
> +    public void flushFriendInfo(Member targetMember, Member deletedMember) {
옮겼어용~

2021-08-29 07:02 UTC, alertjjm commented on src/main/java/com/meme/ala/domain/event/component/EventHandler.java
> +                .removeIf(f -> f == deletedMember.getId());
관계 파악안하고 전부다 pending, friend관계에서 다 지워줘야해서 다시 업데이트했어!
왜냐면 A가 B에게 친구신청하고 A가 탈퇴하고 B가 수락하면 또 에러처리해줘야하니까 그냥 다 지워주려고

2021-08-29 07:03 UTC, alertjjm commented
https://github.com/dnd-side-project/dnd-5th-5-backend/pull/183/commits/c8ad94c3b3cadead66c9cd045bf06b7ba30c9a8c

@Catnap421

2021-08-29 07:10 UTC, Catnap421 approved these changes

2021-08-29 14:29 UTC, merged